highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Simply just
url: denitsa-cm.github.io
baseurl: /simply-just
paginate: 5

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Simply just

description: Stylish Jekyll Theme
author:
  name: Denitsa Damm
  github: denitsa-cm
  twitter: StepToMe_
  linkedin: dmlechkova
  bio: Random thoughts and code things

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: /simply-just

plugins:
  - jekyll-paginate
